INSERT INTO `__dbname__`.`Organisation` VALUES (1001,'Projekt 42','','Wellness Centre',NULL,NULL,'ChIJq6pqJQ-4h0gRX0TqSLTYYjI',NULL,NULL),
(1002,'In Care Survivor Service Scotland','','Trauma specialist counselling and advocacy support service for adults who suffered childhood abuse in care',NULL,NULL,'ChIJGW3YTCh6iEgRj_ksAj5FTOE',NULL,NULL),
(1003,'PF Counselling Service','','Enable people to embrace life more fully through the growth, changes and healing that can take place through the counselling process',NULL,NULL,'ChIJUQQKjQvHh0gRgUA91UEE3Bw',NULL,NULL),
(1004,'Beat','https://www.beateatingdisorders.org.uk/assets/images/f-logo.jpg','You are never alone with your eating disorder',NULL,NULL,'ChIJUx7Beunj2UcR1CxPeAzHmuU',NULL,NULL),
(1005,'Mind The Men','https://mindthemen.co.uk/wp-content/uploads/2019/11/mind-the-men-asset_logo-150x150.png','Suicide prevention peer to peer support group for 18+ men',NULL,NULL,'',NULL,NULL),
(1006,'Breathing Space','https://breathingspace.scot/img/toplogo.png','Sometimes our thoughts and feelings can overwhelm us. It helps to get some Breathing Space.',NULL,NULL,'',NULL,NULL),
(1007,'Samaritans ','','Whatever you\'re going through, a Samaritan will face it with you.',NULL,NULL,'',NULL,NULL),
(1008,'Alternatives Dundee Youth','','Support young people aged 12-25, in need of additional support particularly in the areas of low self esteem, relationships and/ or emotional well being. ',NULL,NULL,'ChIJiZnwNuhchkgR1dmzfPEyVT8',NULL,NULL),
(1009,' Aberlour Outreach (Dundee) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1010,' Tayside Arrest Referral Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1011,' We Are With You (Fife) ','https://www.wearewithyou.org.uk/static/img/logo/brand-logo-stacked.85d318636c49.svg','Community Based',NULL,NULL,'',NULL,NULL),
(1012,' We Are With You (Islay) ','https://www.wearewithyou.org.uk/static/img/logo/brand-logo-stacked.85d318636c49.svg','Community Based',NULL,NULL,'',NULL,NULL),
(1013,' We Are With You (Argyll & Bute) ','https://www.wearewithyou.org.uk/static/img/logo/brand-logo-stacked.85d318636c49.svg','Community Based',NULL,NULL,'',NULL,NULL),
(1014,' We Are With You (Dumfries) ','https://www.wearewithyou.org.uk/static/img/logo/brand-logo-stacked.85d318636c49.svg','Community Based',NULL,NULL,'',NULL,NULL),
(1015,' We Are With You (Stranraer) ','https://www.wearewithyou.org.uk/static/img/logo/brand-logo-stacked.85d318636c49.svg','Community Based',NULL,NULL,'',NULL,NULL),
(1016,' We Are With You - Dundee Direct Access Service ','https://www.wearewithyou.org.uk/static/img/logo/brand-logo-stacked.85d318636c49.svg','Community Based',NULL,NULL,'',NULL,NULL),
(1017,' We Are With You - East Ayrshire Recovery Service ','https://www.wearewithyou.org.uk/static/img/logo/brand-logo-stacked.85d318636c49.svg','Community Based',NULL,NULL,'',NULL,NULL),
(1018,' We Are With You - Families Plus Service ','https://www.wearewithyou.org.uk/static/img/logo/brand-logo-stacked.85d318636c49.svg','Community Based',NULL,NULL,'',NULL,NULL),
(1019,' We Are With You - North West Recovery Hub (Glasgow) ','https://www.wearewithyou.org.uk/static/img/logo/brand-logo-stacked.85d318636c49.svg','Community Based',NULL,NULL,'',NULL,NULL),
(1020,' We Are With You - South Ayrshire Recovery Service ','https://www.wearewithyou.org.uk/static/img/logo/brand-logo-stacked.85d318636c49.svg','Community Based',NULL,NULL,'',NULL,NULL),
(1021,' Addiction Recovery Centre (Kirkintilloch) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1022,' Addiction Services (NHS Borders) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1023,' Addiction Services (NHS Fife) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1024,' Addictions Support and Counselling (ASC) Forth Valley (Falkirk) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1025,' Adolescent Substance Use Service (ASUS) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1026,' Adolescent Substance Use Service (ASUS) (East Lothian) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1027,' Angus Integrated Drug & Alcohol Recovery Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1028,' Alcohol & Drugs Action ','','Community Based',NULL,NULL,'',NULL,NULL),
(1029,' Alcohol Drugs Support South West Scotland (Castle Douglas) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1030,' Alcohol Drugs Support South West Scotland (Dumfries) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1031,' Alcohol Drugs Support South West Scotland (Stranraer) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1032,' Youth Action Team (Inverness) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1033,' Drug Treatment & Testing Order (Dundee) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1034,' Drug Treatment & Testing Order (Edinburgh, East and Midlothian) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1035,' West Lothian NHS Addiction Service ','','Community Based, Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1036,' Drug Treatment & Testing Order (Fife) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1037,' West Lothian Drug and Alcohol Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1038,' Drug Treatment & Testing Order (Glasgow) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1039,' Alternatives (Clydebank) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1040,' Drug Treatment & Testing Order (Highland) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1041,' Alcohol and Drug Recovery Service (Glasgow West) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1042,' Drug Treatment & Testing Order (Inverclyde) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1043,' Alternatives (Dumbarton) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1044,' Drug Treatment & Testing Order (Lanarkshire) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1045,' Web Project (Angus) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1046,' Apex Scotland Services (Stranraer) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1047,' Drug Treatment & Testing Order (Renfrewshire) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1048,' Web Project / Streets Ahead ','','Community Based',NULL,NULL,'',NULL,NULL),
(1049,' Drug Treatment & Testing Order (West Lothian) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1050,' Alcohol and Drug Recovery Service (Glasgow East) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1051,' East Dunbartonshire Alcohol and Drugs Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1052,' Apex Scotland Services (Dumfries) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1053,' Veterans Substance Misuse Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1054,' East Lothian Substance Misuse Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1055,' East Renfrewshire Community Addiction Team ','','Community Based',NULL,NULL,'',NULL,NULL),
(1056,' East Renfrewshire Community Recovery Team ','','Community Based',NULL,NULL,'',NULL,NULL),
(1057,' Edinburgh Access Practice ','','Community Based',NULL,NULL,'',NULL,NULL),
(1058,' Eriskay House ','','Community Based',NULL,NULL,'',NULL,NULL),
(1059,' FASS Community Drug Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1060,' Fife Intensive Rehabilitation Substance Misuse Team (FIRST) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1061,' Argyll & Bute Addiction Service (Oban) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1062,' First Base Agency ','','Community Based',NULL,NULL,'',NULL,NULL),
(1063,' Forth Valley Substance Misuse Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1064,' Glasgow Drug Crisis Centre (Turning Point Scotland) ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1065,' Argyll & Bute Addiction Team (Bute) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1066,' Turning Point Scotland - Edinburgh Substance Misuse Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1067,' North Aberdeenshire Recovery Service (Banff) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1068,' North Aberdeenshire Recovery Service (Peterhead) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1069,' Turning Point Scotland (218 Service) ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1070,' Turnaround Residential Unit (Paisley) ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1071,' Teen Challenge UK ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1072,' Integrated Substance Misuse Team (Dundee) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1073,' Tayside Council on Alcohol - Adult Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1074,' Argyll & Bute Addiction Team (Cowal) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1075,' Argyll & Bute Addiction Team (Kintyre) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1076,' Argyll & Bute Addiction Team (Mid Argyll) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1077,' Crossreach Tayside Support Services ','','Community Based',NULL,NULL,'',NULL,NULL),
(1078,' Barnardo\'s Axis Service (Falkirk) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1079,' Barnardo\'s Connect (Aberdeen) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1080,' Barnardo\'s Freagarrach Project (Stirling) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1081,' Barnardo\'s Threads (Paisley) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1082,' Community Mental Health Team (Orkney) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1083,' Community Addiction Recovery Service (CAReS) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1084,' Substance Misuse Service - South West Recovery Hub ','','Community Based',NULL,NULL,'',NULL,NULL),
(1085,' Substance Misuse Service (Grampian) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1086,' Substance Misuse Service - South East Recovery Hub ','','Community Based',NULL,NULL,'',NULL,NULL),
(1087,' Substance Misuse Service - North West Recovery Hub ','','Community Based',NULL,NULL,'',NULL,NULL),
(1088,' Bethany Christian Centre ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1089,' Black & Minority Ethnic Drug & Alcohol Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1090,' Cairn Centre Harm Reduction Service (Dundee) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1091,' Caithness Alcohol and Drug Service (Thurso) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1092,' Substance Misuse Service - North East Recovery Hub ','','Community Based',NULL,NULL,'',NULL,NULL),
(1093,' Caithness Alcohol and Drug Service (Wick) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1094,' Substance Misuse In-patient Service (Inverness) ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1095,' Castle Craig Hospital ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1096,' Substance Misuse Co-ordinator (Western Isles)  ','','Community Based',NULL,NULL,'',NULL,NULL),
(1097,' Circle (Harbour Project) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1098,' Circle (West Lothian) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1099,' NHS Specialist Drug and Alcohol Service (Dumfries & Galloway) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1100,' Clued Up Project ','','Community Based',NULL,NULL,'',NULL,NULL),
(1101,' Special Needs in Pregnancy Services (Renfrewshire) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1102,' West Dunbartonshire Addiction Services (Clydebank) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1103,' Community Alcohol & Drug Service (Forth Valley) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1104,' Special Needs in Pregnancy Services (Inverclyde) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1105,' Special Needs in Pregnancy Services (Glasgow) ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1106,' Special Needs in Pregnancy Services (Dunbartonshire) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1107,' Harm Reduction Team NHS Lothian ','','Community Based',NULL,NULL,'',NULL,NULL),
(1108,' Community Substance Misuse Service (Aberdeenshire) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1109,' Connecting Carers ','','Community Based',NULL,NULL,'',NULL,NULL),
(1110,' Cothrom Eile ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1111,' CPN Team (Lewis & Harris) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1112,' CPN Team (Uists & Barra) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1113,' CREW ','','Community Based',NULL,NULL,'',NULL,NULL),
(1114,' Drugs Alcohol & Psychotherapies Limited (DAPL) services for young people ','','Community Based',NULL,NULL,'',NULL,NULL),
(1115,' Drugs Alcohol & Psychotherapies Limited (DAPL) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1116,' Perth & Kinross Drug and Alcohol Team ','','Community Based',NULL,NULL,'',NULL,NULL),
(1117,' Drug Court Supervision & Treatment Team (Glasgow) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1118,' Drug Liaison Midwife ','','Community Based',NULL,NULL,'',NULL,NULL),
(1119,' Drug Treatment & Testing Order (Aberdeen City) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1120,' Drug Treatment & Testing Order (Argyll, Bute and Dunbartonshire) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1121,' Drug Treatment & Testing Order (Ayrshire Criminal Justice Partnership) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1122,' Drug Treatment & Testing Order (Borders) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1123,' Drug Treatment & Testing Order (Dumfries & Galloway) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1124,' Substance Misuse Recovery Service (Shetland) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1125,' Alcohol and Drug Recovery Service (Glasgow South West) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1126,' Alcohol and Drug Recovery Service (Glasgow South East) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1127,' Alcohol and Drug Recovery Service (Glasgow Greater Pollok) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1128,' Highland Alcohol and Drug Advice & Support Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1129,' Harm Reduction Service (Lanarkshire) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1130,' Alcohol and Drug Recovery Service (Glasgow South) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1131,' South Ayrshire Health & Social Care Partnership Community NHS Addiction Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1132,' Social Work Department (Renfrew Area Office) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1133,' Social Work Addictions Team (West Lothian) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1134,' Simpson House Counselling and Recovery Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1135,' Second Chance Project ','','Community Based',NULL,NULL,'',NULL,NULL),
(1136,' Scottish Borders CHIMES Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1137,' Salvation Army (Falkirk) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1138,' Routes Out ','','Community Based',NULL,NULL,'',NULL,NULL),
(1139,' Ritson Clinic ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1140,' Re-Solv (Scotland) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1141,' Renfrewshire Drug Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1142,' Helensburgh and Lomond Addiction Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1143,' Drug & Alcohol Intervention Team ','','Community Based',NULL,NULL,'',NULL,NULL),
(1144,' Homeless Addiction Team (Glasgow) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1145,' Homeless Outreach Project ','','Community Based',NULL,NULL,'',NULL,NULL),
(1146,' Integrated Drug Service (Aberdeen) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1147,' Alcohol and Drug Recovery Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1148,' Rankeillor Initiative ','','Community Based',NULL,NULL,'',NULL,NULL),
(1149,' Rainbow House ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1150,' Priory Addiction Treatment Programme ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1151,' ISSU 18 (Young People\'s Substance Use) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1152,' Pre Birth Team (New Expectations) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1153,' Addiction Recovery Team (Airdrie) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1154,' Addiction Recovery Team (Bellshill) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1155,' Jericho House (Men Only) ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1156,' Addiction Recovery Team (Coatbridge) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1157,' Phoenix Futures ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1158,' Addiction Recovery Team (Cumbernauld) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1159,' Addiction Recovery Team (Motherwell) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1160,' Addiction Recovery Team (Wishaw) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1161,' Glasgow Image and Performance Enhancing Drugs Clinic (IPEDS) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1162,' LEAP (Lothian & Edinburgh Abstinence Programme) ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1163,' Web Project Key to Change ','','Community Based',NULL,NULL,'',NULL,NULL),
(1164,' Kintyre Alcohol and Drugs Advisory Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1165,' West Dunbartonshire Addiction Services (Dumbarton) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1166,' Ward 5 Inpatient Addiction Services ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1167,' Liber8 (Lanarkshire) Ltd ','','Community Based',NULL,NULL,'',NULL,NULL),
(1168,' Over-Count Drugs Information Agency ','','Community Based',NULL,NULL,'',NULL,NULL),
(1169,' Change Grow Live North West ','','Community Based',NULL,NULL,'',NULL,NULL),
(1170,' Change Grow Live South East ','','Community Based',NULL,NULL,'',NULL,NULL),
(1171,' Osprey House ','','Community Based',NULL,NULL,'',NULL,NULL),
(1172,' Change Grow Live South West ','','Community Based',NULL,NULL,'',NULL,NULL),
(1173,' Mid and East Lothian Drugs (MELD) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1174,' Moving On (Inverclyde) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1175,' Orkney Alcohol Counselling & Advisory Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1176,' Midpark Hospital ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1177,' North Ayrshire Drug & Alcohol Recovery Service (NADARS) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1178,' Oban Addiction Support and Information Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1179,' North Edinburgh Drug & Alcohol Centre/Complex & Multiple Needs Team ','','Community Based',NULL,NULL,'',NULL,NULL),
(1180,' Alcohol and Drug Recovery Service (Glasgow North East) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1181,' Midlothian Young People\'s Advice Service (MYPAS) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1182,' Addiction Services NHS (East Ayrshire) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1183,' Alcohol, Drugs BBV Social Work Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1184,' Substance Misuse Service (Midlothian) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1185,' Health Opportunities Team (HOT) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1186,' Jericho House (Women Only) ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1187,' The Junction, Young People, Health & Wellbeing ','','Community Based',NULL,NULL,'',NULL,NULL),
(1188,' We Are With You - Borders ','','Community Based',NULL,NULL,'',NULL,NULL),
(1189,' Abbeycare Scotland ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1190,' North Aberdeenshire Drug & Alcohol Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1191,' Survivor Trauma Abuse and Addictions Recovery Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1192,' Argyll & Bute Addiction Team (Islay) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1193,' Hillcrest Futures ','','Community Based',NULL,NULL,'',NULL,NULL),
(1194,' Relationships Scotland Orkney ','','Community Based',NULL,NULL,'',NULL,NULL),
(1195,' Tayside Council on Alcohol - Young Person Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1196,' Multiple Needs Charity 1','','Dummy Organisation to Test behaviour',NULL,NULL,'',NULL,NULL),
(1197,' Charity with 2 Needs','','Dummy Org to Test App Behaviour',NULL,NULL,'',NULL,NULL),
(1198,' Dummy Charity with 1 Need','','Dummy Org to Test App Behaviour',NULL,NULL,'',NULL,NULL);
