
Insert into __dbname__.Country values(101,'Scotland');
Insert into __dbname__.Country values(102,'England');
Insert into __dbname__.Country values(103,'Wales');
Insert into __dbname__.Country values(104,"Northen Ireland");
Insert into __dbname__.Country values(105,"United Kingdom");
Insert into __dbname__.Gender values(101,'Female');
Insert into __dbname__.Gender values(102,'Male');
Insert into __dbname__.Gender values(103,'Both');

Insert into __dbname__.Needs Values(101,'Abuse','Abuse or Bullying');
Insert into __dbname__.Needs Values(102,'Addiction','Addiction');
Insert into __dbname__.Needs Values(103,'Alcohol','Addiction');
Insert into __dbname__.Needs Values(104,'Anger','Anxiety, Anger or Stress');
Insert into __dbname__.Needs Values(105,'Anxiety','Anxiety, Anger or Stress');
Insert into __dbname__.Needs Values(106,'Bereavement','');
Insert into __dbname__.Needs Values(107,'Body image','Body image or Eating disorders');
Insert into __dbname__.Needs Values(108,'Bullying','Abuse or Bullying');
Insert into __dbname__.Needs Values(109,'Care','');
Insert into __dbname__.Needs Values(110,'Debt','Debt or Unemployment');
Insert into __dbname__.Needs Values(111,'Depression','Feeling low or Depressed');
Insert into __dbname__.Needs Values(112,'Discrimination','');
Insert into __dbname__.Needs Values(113,'Domestic Abuse','Domestic Abuse');
Insert into __dbname__.Needs Values(114,'Drugs','Addiction');
Insert into __dbname__.Needs Values(115,'Eating disorders','Body image or Eating disorders');
Insert into __dbname__.Needs Values(116,'Feeling low','Feeling low or Depressed');
Insert into __dbname__.Needs Values(117,'Gender identity','LGBTQ+ or Gender identity');
Insert into __dbname__.Needs Values(118,'General Mental Health','');
Insert into __dbname__.Needs Values(119,'Into work /unemployment','Debt or Unemployment');
Insert into __dbname__.Needs Values(120,'Involved in crime','Crime');
Insert into __dbname__.Needs Values(121,'LGBTQ+','LGBTQ+ or Gender identity');
Insert into __dbname__.Needs Values(122,'Loneliness','');
Insert into __dbname__.Needs Values(123,'Money','Debt or Unemployment');
Insert into __dbname__.Needs Values(124,'New parent','Pregnancy and Parenting');
Insert into __dbname__.Needs Values(125,'Panic Attacks','Anxiety, Anger or Stress');
Insert into __dbname__.Needs Values(126,'Parenting','Pregnancy and Parenting');
Insert into __dbname__.Needs Values(127,'Pregnant','Pregnancy and Parenting');
Insert into __dbname__.Needs Values(128,'Ralationship issue','');
Insert into __dbname__.Needs Values(129,'Self harm','Suicide or Self-harm');
Insert into __dbname__.Needs Values(130,'Sleep','Sleeping problems');
Insert into __dbname__.Needs Values(131,'Stress','Anxiety, Anger or Stress');
Insert into __dbname__.Needs Values(132,'Suicide','Suicide or Self-harm');
Insert into __dbname__.Needs Values(133,'Victim of crime','Crime');

Insert into __dbname__.Type Values(101,'Information','Information');
Insert into __dbname__.Type Values(102,'Helpline','Talk to someone');
Insert into __dbname__.Type Values(103,'Face to Face Counselling','Talk to someone');
Insert into __dbname__.Type Values(104,'Free services','Free services');
Insert into __dbname__.Type Values(105,'Financial help','Financial help');
Insert into __dbname__.Type Values(106,'Support groups','Support groups');
Insert into __dbname__.Type Values(107,'Self Help','Self Help');
Insert into __dbname__.Type Values(108,'Community care','Community care');
Insert into __dbname__.Type Values(109,'Online support - Message Boards','Online support');
Insert into __dbname__.Type Values(110,'Online support - Video Support Group','Online support');
Insert into __dbname__.Type Values(111,'Online support - Chat','Online support');
Insert into __dbname__.Type Values(112,'Online support - Text Counselling','Online support');
Insert into __dbname__.Type Values(113,'Online support - E-Counselling','Online support');
Insert into __dbname__.Type Values(114,'Online support - Video Counselling','Online support');

Insert into __dbname__.Personalisation Values(101,'Under 16','Under 18');
Insert into __dbname__.Personalisation Values(102,'16+','');
Insert into __dbname__.Personalisation Values(103,'18+','');
Insert into __dbname__.Personalisation Values(104,'A student','A student');
Insert into __dbname__.Personalisation Values(105,'A parent','A parent');
Insert into __dbname__.Personalisation Values(106,'LGBTQ+','LGBTQ+');
Insert into __dbname__.Personalisation Values(107,'Unemployed','Unemployed');
Insert into __dbname__.Personalisation Values(108,'A carer','A carer');
Insert into __dbname__.Personalisation Values(109,'BAME','BAME');


