INSERT INTO `Miricyl`.`Organisation` 
(`OrgID`,`OrgName`,`LogoURl`,`ServiceDesc`,`Email`,`OrgURL`,`PlaceID`,`Country_CountryID`,`NationalService`)
VALUES (1001,'@Scott Street','','Service which offers guidance, support, information and signposting for young people.',NULL,NULL,'ChIJ67phyRY7hkgRLX2LuPbb21Y',NULL,NULL),
(1002,'6VT Edinburgh City Youth Cafe','https://static.wixstatic.com/media/1df839_f24917bd256c4919b40b9156d3d40d2d~mv2.png/v1/fill/w_545,h_286,al_c,q_85,usm_1.20_1.00_0.01/6VTblue%26title.webp','The Cairn service provides support for young victims and witnesses of crime is run by staff and volunteers.',NULL,NULL,'ChIJB8wvxpvHh0gRHJzphn5vYHY',NULL,NULL),
(1003,'Action for Children ','','Help for families with disabled children, and services for young carers. It includes free or low-cost parenting classes through our children\'s centres. It includes running events for prospective foster parents.',NULL,NULL,'ChIJA2F0CvhqdkgROgZCIOuT2XI',NULL,NULL),
(1004,'Addaction','https://www.wearewithyou.org.uk/static/img/logo/brand-logo-stacked.85d318636c49.svg','The service is for people 16 years and over, families and carers who need support around their own or someone else’s drug or alcohol use',NULL,NULL,'ChIJpxvIa76kiUgRWeaJSNije2s',NULL,NULL),
(1005,'Advocard','http://www.advocard.org.uk/wp-content/uploads/2015/06/cropped-AdvoCard-Logo-for-prison.jpg','Advocacy helps you have a stronger voice and a greater chance of influencing decisions about your life.',NULL,NULL,'ChIJhSfWiwq4h0gRHLH6EUB6X5s',NULL,NULL),
(1006,'Akordia','https://arkordia.org/wp-content/uploads/2016/07/arkordialogo.jpg','Low-cost psychotherapy and counselling services if you are on a low income',NULL,NULL,'ChIJB5z5QH_Hh0gRLuQvE_fca5Q',NULL,NULL),
(1007,'Alcohol and Drug Support South West Scotland (ADS)','','A range of community-based services across Dumfries and Galloway. We help people affected by alcohol, drugs or gambling problems.',NULL,NULL,'ChIJv2UuVvTCYkgRDWPUgVXZOdk',NULL,NULL),
(1008,'Alcoholics Anonymous','https://www.addiction.org.uk/wp-content/uploads/2014/01/AA.jpg','Fellowship of men and women who share their experience, strength and hope with each other in the hope it may solve their common problem and help others to recover from alcoholism',NULL,NULL,'ChIJvXE1mQgxeUgRxJEbBS-aCbE',NULL,NULL),
(1009,'All in Edinburgh (Enable Scotland)','http://allinedinburgh.org.uk/wp-content/uploads/2020/09/AiE-Circle.jpg','Supported Employment for people who have a disability or long term health condition in Edinburgh.',NULL,NULL,'ChIJLcl4jSXEh0gRGTbeeWwsZTE',NULL,NULL),
(1010,'Alternatives Dundee Youth','https://alternativesdundee.org/wp-content/uploads/2020/02/cropped-transparent-house-e1581014829915.png','At the Alternatives listening rooms we provide support that is person centred. This means that we provide a  space for you to talk through what has happened, what you are feeling and the decisions you want to make',NULL,NULL,'ChIJ4QlxusFchkgRfIycznmE5h0',NULL,NULL),
(1011,'Alzheimer Scotland','https://ithriveedinburgh.org.uk/wp-content/uploads/2020/09/Alzheimer-Scotland.jpg','The Young Onset service aims to support people with dementia, their families, relatives and friends at any stage of the illness.',NULL,NULL,'ChIJH9kFbCzGh0gRzzdQ8iKOUL0',NULL,NULL),
(1012,'Amina-the Muslim Women’s Resource Centre','https://mwrc.org.uk/wp-content/themes/amina/images/logo.png','Amina’s ‘Ending Violence against Women and Girls’ (VAWG) programme is a prevention programme which aims to challenge sexist and misogynistic attitudes and behaviours amongst the Muslim and Black and Minority Ethnic (BME) communities',NULL,NULL,'ChIJlQFpglBGiEgRve0_SJuXUuM',NULL,NULL),
(1013,'Angus Young Carers Project','http://www.angusyoungcarers.org.uk/img/layout/logo.png','Carers in Angus will receive appropriate information and support to enable them to feel valued and confident in their caring situation and to develop their own potential',NULL,NULL,'ChIJ0V1bGhqNhkgRukV66iGikcw',NULL,NULL),
(1014,'Apex Scotland','','Training programme to help young people aged 16+ to take steps towards employment',NULL,NULL,'ChIJdYhlWLzHh0gR5vdWxRLDXzs',NULL,NULL),
(1015,'Argyll and Bute Addiction Team','','An integrated team comprising staff from NHS Highland and Argyll and Bute Council.  Staff include Social Workers, Nurses and a Psychiatrist all of whom are specialists in addiction work',NULL,NULL,'ChIJZZKxEUuCiUgRHBSrGzOS7DE',NULL,NULL),
(1016,'Argyll and Bute Homeless Service','https://www.argyll-bute.gov.uk/sites/default/files/sky/logo.png','Help with emergency accomodation, permanent housing, advice on the legal rights of spouses and co-habitees, and referral to support agencies.',NULL,NULL,'ChIJ49pmUekGikgRKRATGoVq8hs',NULL,NULL),
(1017,'Arts Therapies (NHS Lothian)','https://services.nhslothian.scot/ArtsTherapies/PublishingImages/Pages/Arts%20Therapies%20Service/ARTS_THERAPIES_BLACK%20no%20dots%20crop.jpeg','Arts Therapies are person-centred psychological therapies that are based across NHS Lothian',NULL,NULL,'ChIJORUPIw7Hh0gRiqJIqoWLPwA',NULL,NULL),
(1018,'ASH Scotland (Action on Smoking and Health)','https://impact.scot/wp-content/uploads/2019/02/IMPACT-logo.jpg','The IMPACT Project provides free training and resources to workers and volunteers from the Third Sector and the NHS about the adverse effects on mental health of smoking tobacco.',NULL,NULL,'ChIJb5B7OpfHh0gR85ntdaRfVag',NULL,NULL),
(1019,'Autism Initiatives UK','https://www.autisminitiatives.org/assets/images/autism-logo-1cbdc36ccf.png','Number 6 provides free social opportunities and one-to-one advice and support on a range of issues.',NULL,NULL,'ChIJI6w-5ZbHh0gRtfzbIbdKbTU',NULL,NULL),
(1020,'Beat','https://www.beateatingdisorders.org.uk/assets/images/f-logo.jpg','UK’s eating disorder charity',NULL,NULL,'ChIJUx7Beunj2UcR1CxPeAzHmuU',NULL,NULL),
(1021,'Befriending Network','https://www.befriending.co.uk/img/befriending-networks-logo-2011.png','Befriending Networks is a third sector intermediary that provides support, training and resources for befriending services throughout the UK, but does not directly provide befriending',NULL,NULL,'ChIJ_V-4J6PHh0gRHnFkg_WLJ64',NULL,NULL),
(1022,'Birthlink','http://www.birthlink.org.uk/wp-content/uploads/2015/03/Screen-Shot-2015-03-19-at-16.05.00-e1426781260443.png','Affected by an adoption with a Scottish connection in any way, as a child, parent or relative, and are either looking for somebody, some information, or just someone to talk to, we can help you.',NULL,NULL,'ChIJuTTAB5fHh0gR35s9mh7yJtA',NULL,NULL),
(1023,'Breathing Space','https://breathingspace.scot/img/toplogo.png','Sometimes our thoughts and feelings can overwhelm us. It helps to get some Breathing Space.',NULL,NULL,'ChIJq6qqOtqoiUgRRfE_ePfDwNI',NULL,NULL),
(1024,'Campaign Against Living Miserably (CALM)','https://www.thecalmzone.net/wp-content/themes/CALMV4/assets/images/logo-blue-fixed.png','leading a movement against suicide',NULL,NULL,'',NULL,NULL),
(1025,'Canongate Youth','https://canongateyouth.org.uk/wp-content/uploads/2020/09/CY_MASTER_RGB_NOSTRAP.jpg','Canongate Youth provides employability and wellbeing support to young people aged 15 to 24.',NULL,NULL,'ChIJn1ojzoXHh0gRZq0xxkiSzPU',NULL,NULL),
(1026,'CAPS Independent Advocacy','','Experiences of Psychosis is a collective advocacy group for people with experience of psychosis.',NULL,NULL,'ChIJZzVRIH65h0gRhPmyPa7cP9Q',NULL,NULL),
(1027,'Caring in Craigmillar','','Phonelink is a telephone morning and evening check call service for people aged 65 year olds and over and living Edinburgh.',NULL,NULL,'ChIJFRt_kvm4h0gR2qBMXj_d-4g',NULL,NULL),
(1028,'CoCo Counselling in Communities','http://www.cocoed.org.uk/uploads/6/0/9/4/60945759/1442491566.png','CoCo Counselling is an Edinburgh based community counselling service offering one-to-one counselling and psychotherapy for adults and young people',NULL,NULL,'ChIJk8l32obHh0gRndvA1Sh58FA',NULL,NULL),
(1029,'Crew','https://mk0crewscotb6dvcp91y.kinstacdn.com/wp-content/uploads/2018/09/crew-logo-7fba00.png','Crew provides up to 30 free counselling sessions for people concerned about their stimulant and other drug use',NULL,NULL,'ChIJfT-3h4_Hh0gR3uYGpn6qE3g',NULL,NULL),
(1030,'Crisis','https://www.crisis.org.uk/media/1001/logo.png','Crisis Skylight Edinburgh offers a range of services for people who are homeless and vulnerably housed.',NULL,NULL,'ChIJV9ELGojHh0gRZdSmVbsrLKg',NULL,NULL),
(1031,'CrossReach','https://www.crossreach.org.uk/themes/crossreach/images/logo.svg','CrossReach provides a range of counselling services to individuals, families, children and young people.',NULL,NULL,'ChIJga8K9JbHh0gRPtaoEcuZv4U',NULL,NULL),
(1032,'Crossreach','https://www.crossreach.org.uk/themes/crossreach/images/logo.svg','Simpson House offers support to anyone in Edinburgh who has been affected by past or present drug use, whether it’s your own or someone else’s.',NULL,NULL,'ChIJga8K9JbHh0gRPtaoEcuZv4U',NULL,NULL),
(1033,'Cyrenians','','The Scottish Centre for Conflict Resolution (SCCR) is a national resource centre promoting and supporting best practice in mediation, family conflict resolution and early intervention work with a particular focus around young people and families.',NULL,NULL,'ChIJN2anxXK4h0gRLrDsaqQeJhE',NULL,NULL),
(1034,'Dads Rock','https://ithriveedinburgh.org.uk/wp-content/uploads/2020/09/Dads-Rock.jpg','Dads Rock aims to help improve confidence and resilience of young dads, supporting practical parenting as well as emotional support.',NULL,NULL,'',NULL,NULL),
(1035,'Department of Work and Pensions (DWP)','','The jobcentre has a range of services available to help you return to or move closer to work, especially if you are on a health journey and unsure of what the next step is.',NULL,NULL,'ChIJt-Cj3pjHh0gRNSX6YHRhR9Q',NULL,NULL),
(1036,'EARS Advocacy','https://www.ears-advocacy.org.uk/wordpress/wp-content/themes/ears/images/ears-logo.gif','EARS provides free and confidential independent advocacy support to anyone who has had a stroke within the last two years in the Edinburgh area',NULL,NULL,'',NULL,NULL),
(1037,'Edinburgh and Lothian Council on Alcohol','','Edinburgh and Lothian Council on Alcohol provides specialist advice, information, one-to-one counselling and support to anyone concerned about their own or someone else’s alcohol use',NULL,NULL,'ChIJ7UPXGZfHh0gR0MJE_Z1lNJk',NULL,NULL),
(1038,'Edinburgh Carer’s Council','https://ithriveedinburgh.org.uk/wp-content/uploads/2020/09/Edinburgh-Carers-Council.jpg','The transitions advocacy service is for families and carers of people in mental health settings within Lothian who are in a period of transition.',NULL,NULL,'ChIJ_-q7CRC4h0gRT7d4U4r5yRg',NULL,NULL),
(1039,'Edinburgh Carers Council','','Edinburgh Carers Council provides a free, independent and confidential advocacy service for unpaid carers/family and relatives supporting someone who is in a hospital or who uses services in Edinburgh and who has dementia, an acquired brain injury, learning disability, or mental health difficulties',NULL,NULL,'ChIJ_-q7CRC4h0gRT7d4U4r5yRg',NULL,NULL),
(1040,'Edinburgh Headway Group','https://www.edinburghheadway.org.uk/images/headway-logo.png?dd=1','Edinburgh Headway Group is a rehabilitation day service for people who have an acquired brain injury and their carers.',NULL,NULL,'ChIJo0X1A_S4h0gRF7FSS8sgfug',NULL,NULL),
(1041,'Edinburgh Leisure','https://www.edinburghleisure.co.uk/img/navlogo.png','Edinburgh Leisure is a charity dedicated to making a positive difference by creating opportunities for everyone to get active, stay active and achieve more',NULL,NULL,'ChIJ7ZNvAjDEh0gRBX3GnQm8jPM',NULL,NULL),
(1042,'Edinburgh Rape Crisis Centre','https://www.ercc.scot/wp-content/uploads/2016/12/ercc_new_logo-1.png','The Still I Am Project (SIA) offers a confidential emotional and counselling support is you have experiences where there was something done to you without your consent, made you feel uncomfortable or confused and any kind pressure',NULL,NULL,'ChIJ18Kbi_LHh0gR6j8FLefGZnw',NULL,NULL),
(1043,'Edinburgh Rehab Centre','https://ithriveedinburgh.org.uk/wp-content/uploads/2020/09/Edinburgh-Rehab-Centre-1024x477.jpg','Edinburgh Rehab Centre provides a complimentary telephone advice service on treatment options for those recovering from alcohol abuse and alcohol addiction, in and around Edinburgh.',NULL,NULL,'ChIJR5uO9ZTHh0gRYARafNUym8Q',NULL,NULL),
(1044,'Edinburgh Women’s Aid','','The drop-in and phone support provides information about choices concerning domestic abuse, such as housing options, benefits, welfare rights and legal issues, as well as emotional support.',NULL,NULL,'ChIJkVTVIb_Hh0gRTIaYcu8msiI',NULL,NULL),
(1045,'Enable Scotland','https://www.enable.org.uk/wp-content/themes/enable-scotland/images/logo.png','The Employability Fund programme allows people with learning disabilities and or learning difficulties to develop the skills and experience necessary to progress through the employability pipeline.',NULL,NULL,'ChIJhdYBp4ZriEgRAZNiYorwKT8',NULL,NULL),
(1046,'Eric Liddel Centre','https://www.ericliddell.org/wp-content/uploads/2017/11/logo-web.png','A befriending project specifically for carers. Befriending aims to provide a social outlet and a break from your caring responsibilities.',NULL,NULL,'ChIJ5WJ2jQvHh0gR22V5159Kv_I',NULL,NULL),
(1047,'Family Advice Information Resource (FAIR)','https://www.fairadvice.org.uk/images/logo_home.jpg','FAIR (Family Advice Information Resource) is a specialist charity that provides an information and advice service for people with learning disabilities, parents, carers and people who work with them in Edinburgh.',NULL,NULL,'ChIJg5bBE3_Hh0gRwNRovJXOLuY',NULL,NULL),
(1048,'Fast Forward','','Fast Forward enables young people to make informed choices about their health and wellbeing.',NULL,NULL,'ChIJGfkRIAW4h0gRUgrYg7Gg2Zg',NULL,NULL),
(1049,'Feniks','https://www.feniks.org.uk/feniks/wordpress/wp-content/uploads/2016/12/feniks_logo-1.jpg?x83021','Supporting integration and aiming at improving the wellbeing of the Central Eastern European Community in Edinburgh',NULL,NULL,'ChIJLSSirG64h0gRQuhhK7wcsVY',NULL,NULL),
(1050,'Firsthand Lothian','https://ithriveedinburgh.org.uk/wp-content/uploads/2020/09/First-Hand.jpg','Time 4 Mum helps isolated mums, who have childcare in place, explore and participate in activities in their local community.',NULL,NULL,'ChIJTR9v1vTHh0gRS9HYeRK5eYk',NULL,NULL),
(1051,'Foundation for Positive Mental Health','https://www.foundationforpositivementalhealth.com/wp-content/uploads/2015/12/cloud-logo.png','Foundation for Positive Mental Health provides mental health training for NHS service providers, carers and workplaces.',NULL,NULL,'ChIJe5ZmXd7Hh0gRZDVGPBlvmo0',NULL,NULL),
(1052,'Fresh Start','','The Hit Squad is made up of staff and volunteer and can help you decorate up to 2 rooms in your new home if have moved into it within the last 12 month. You can pick the colours and help out the Hit Squad team on the day',NULL,NULL,'ChIJy4k0fDLGh0gRPhnavV_xZu0',NULL,NULL),
(1053,'Future Pathways','https://future-pathways.co.uk/wp-content/uploads/elementor/thumbs/logo-future-pathways-oa4pfe7cr4e5543ahukzlfcwjltoo1u1o64dzl7eyi.png','For people who have experienced abuse or neglect when they were under the age of 18, in Scotland, within a care settin',NULL,NULL,'',NULL,NULL),
(1054,'Grassmarket Community Project','https://grassmarket.org/wp-content/uploads/2019/02/grassmarket-logo-cp.png','The Grassmarket Community Project takes an innovative approach to creating community, providing sanctuary and support to people dealing with multiple complex issues. These include homelessness, mental/physical health problems, learning difficulties, poverty, substance misuse, physical abuse and more',NULL,NULL,'ChIJbfOe2vnHh0gRKhwN_-aAG_s',NULL,NULL),
(1055,'Health in Mind','https://www.health-in-mind.org.uk/images/health-in-mind.svg','Friendly peer-led support group open to any adults living with depression, low mood, stress or anxiety',NULL,NULL,'ChIJLYBG1aLHh0gRUPEEVORG1nc',NULL,NULL),
(1056,'Held in Our Hearts','https://heldinourhearts.org.uk/wp-content/uploads/2019/12/HIOH_Logo.png',' Support to bereaved families',NULL,NULL,'ChIJpZ7LVeLGh0gRSHy3D6rUW9c',NULL,NULL),
(1057,'HIV Scotland','https://ithriveedinburgh.org.uk/wp-content/uploads/2020/10/HIV-Scotland.jpg','The project provides one-to-one counselling, therapy or life coaching for people living with HIV, their partners or family members. ',NULL,NULL,'ChIJsSp3-43Hh0gRokNC9ovNphM',NULL,NULL),
(1058,'Home-Start Edinburgh West and South','http://www.hsew.org.uk/_/rsrc/1571310441871/home/hs_quality_orange_keyline_HR.jpg?height=200&width=151','The aim of this service is to work with referrers and families to introduce them to Home-Start Edinburgh West and South West (HSEW) and build a relationship with the parent/carer and their family in an environment where they feel saf',NULL,NULL,'',NULL,NULL),
(1059,'In Care Survivor Service Scotland','','Trauma specialist counselling and advocacy support service for adults who suffered childhood abuse in care',NULL,NULL,'ChIJGW3YTCh6iEgRj_ksAj5FTOE',NULL,NULL),
(1060,'IWORK4ME','','IWORK4ME exists to promote the benefits of supported self-employment to autistic adults across Scotland and in turn support clients to take a hobby or interest and very slowly, at a rate to suit, build a small micro-enterprise',NULL,NULL,'ChIJ_ewd9tfHh0gRic2ZyYzhOhU',NULL,NULL),
(1061,'Juno Perinatal Mental Health Support','','Perinatal Mental Health Support groups for mums and mums-to-be who are struggling emotionally.',NULL,NULL,'',NULL,NULL),
(1062,'LGBT Youth Scotland','','A youth service for lesbian, gay, bisexual and transgender young people aged 13-25 years old',NULL,NULL,'ChIJ0fTYPetchkgR4C6OA5G8GXQ',NULL,NULL),
(1063,'Lothian Bipolar Self-help Group','https://lothianbipolargroup.org.uk/wp-content/uploads/2017/03/LBG-Red-Logo.png','Lothian Bipolar Self-help Group that aims to bring people together who want to provide information, peer support and self-management guidance. Group members have their own experience of bipolar and help each other to stay well.',NULL,NULL,'',NULL,NULL),
(1064,'Mind The Men','https://mindthemen.co.uk/wp-content/uploads/2019/11/mind-the-men-asset_logo-150x150.png','Suicide prevention peer to peer support group for 18+ men',NULL,NULL,'',NULL,NULL),
(1065,'Multi-Cultural Family Base','','Children and their families who are experiencing difficulties. Some of these are practical, such as housing or financial problems; others are more personal, such as dealing with discrimination or emotional issues.',NULL,NULL,'ChIJ7QPL_wa4h0gRZbyqzse9h-c',NULL,NULL),
(1066,'Networking Key Services (NKS) Ltd.','','Networking Key Services Ltd. aims to reduce deprivation and isolation for South Asian and other ethnic minority women and their families, and promote positive health and wellbeing among them.',NULL,NULL,'ChIJJyjgSaDHh0gREtDc9f3CpCA',NULL,NULL),
(1067,'NHS Lothian','https://www.nhslothian.scot/Style%20Library/Images/tinylogo.png','The Mental Health Information Station is a one-stop-shop for anyone affected by mental health and wellbeing difficulties.',NULL,NULL,'ChIJ6c2vxaTHh0gRSGTkjx6oCMk',NULL,NULL),
(1068,'Nordoff Robbins','','Nordoff Robbins music therapists understand that music evokes different reactions and responses in people.',NULL,NULL,'ChIJFfnb7e3Hh0gRM5wjRcShKgw',NULL,NULL),
(1069,'Partners in Advocacy','https://www.partnersinadvocacy.org.uk/wp-content/uploads/PiA-Logo.jpg','Partners in Advocacy provides confidential independent advocacy',NULL,NULL,'ChIJ_-q7CRC4h0gRT7d4U4r5yRg',NULL,NULL),
(1070,'Penumbra','https://www.penumbra.org.uk/wp-content/themes/penumbra-org-uk/assets/images/penumbra_logo.gif','The Edinburgh Crisis Centre is open 24 hours a day 365 days of the year and provides community-based, emotional and practical support at times of mental health crisis currently through telephone, email or video call.',NULL,NULL,'ChIJ7fI28KDHh0gR4bavkcCSnDI',NULL,NULL),
(1071,'People Know How','https://peopleknowhow.org/wp-content/uploads/2020/02/People-Know-How-Logotype.png','Delivering computers and devices to people who need help staying connected, accessing support or home-schooling during the coronavirus outbreak',NULL,NULL,'ChIJl-1NTszHh0gRrLd2uQs6dFA',NULL,NULL),
(1072,'PF Counselling','https://www.pfcounselling.org.uk/wp-content/uploads/2016/08/HeaderLogoOPS.jpg','PF Counselling Service provides counselling and psychotherapy for people facing the difficulties of everyday life.',NULL,NULL,'ChIJeTbGi-LGh0gRwZZk-eEODsQ',NULL,NULL),
(1073,'PF Counselling Service','','Enable people to embrace life more fully through the growth, changes and healing that can take place through the counselling process',NULL,NULL,'ChIJUQQKjQvHh0gRgUA91UEE3Bw',NULL,NULL),
(1074,'Positive Help','https://www.positivehelpedinburgh.co.uk/wp-content/themes/positivehelpedinburgh/assets/img/images/positivehelp-edinburgh.png','Home support service makes a very direct impact on quality of life for those affected by the symptoms of HIV or Hepatitis C and the often debilitating side effects of combination drugs therapies.',NULL,NULL,'ChIJEz5o0ZfHh0gROQ98B94sJnY',NULL,NULL),
(1075,'Pregnancy Counselling & Care (Scotland)','https://www.counsellingandcare.co.uk/wp-content/uploads//cropped-logo-small-1-1.png','The fast track counselling service provides fast support to anyone who is experiencing mental health difficulties close to giving birth or shortly after finding out they are pregnant.',NULL,NULL,'ChIJVZ-bGIvHh0gRLC69yHvBjzs',NULL,NULL),
(1076,'Projekt 42','','Projekt 42 is the UK’s first wellness centre to combine personal training, group fitness, yoga and mental health services.',NULL,NULL,'ChIJdcX8BRa4h0gR1braGEqWHCY',NULL,NULL),
(1077,'Queen Margaret University','https://ithriveedinburgh.org.uk/wp-content/uploads/2020/10/Queen-Margaret-University.jpg','Queen Margaret University offers short-term counselling, normally up to six sessions, to help you with any personal problems which might be affecting your academic work or your general health and wellbeing.',NULL,NULL,'ChIJFZ8Wqnq5h0gRZmTem1XcsPw',NULL,NULL),
(1078,'Rainbow Recovery','https://rainbowrecovery.org.uk/wp-content/themes/rainbowrecovery/images/logo.png','Rainbow Recovery was established by the wife of an alcoholic who identified that there were very little supports for families suffering from another person’s addiction',NULL,NULL,'ChIJ041PXKrHh0gR-X_mPW_iPsM',NULL,NULL),
(1079,'Samaritans ','','Whatever you\'re going through, a Samaritan will face it with you.',NULL,NULL,'ChIJ98GLB9wJdkgRyjgGlCQ91pw',NULL,NULL),
(1080,'Scottish Association for Mental Health (SAMH)','','The SAMH housing support service can provide you with practical, emotional and social support.',NULL,NULL,'ChIJwc73zRq4h0gRH-HGosLvjHU',NULL,NULL),
(1081,'Scottish Cot Death Trust','https://scottishcotdeathtrust.org/wp-content/uploads/2019/03/scdt-logo-white.png','Provide education for professionals and the public. This education focuses on raising awareness of how we can reduce the risks of sudden and unexpected death in infancy (SUDI) occurring',NULL,NULL,'ChIJX3mF_9lFiEgRPR5sVWT4ukQ',NULL,NULL),
(1082,'Scottish Recovery Network','https://www.scottishrecovery.net/wp-content/themes/SRN/images/logo2020.png','Scottish Recovery Network’s vision and strategic aims are underpinned by its organisational values which are informed by recovery principles',NULL,NULL,'ChIJe-E1c55GiEgRKJur4meUiZ0',NULL,NULL),
(1083,'Shared Care Scotland','https://www.sharedcarescotland.org.uk/wp-content/uploads/2017/04/shared-care-curves.jpg','Shared Care Scotland work towards a vision of Scotland where everyone who provides unpaid care can live a satisfying life, with the assistance they need to take regular, quality breaks',NULL,NULL,'ChIJ38XFAfTRh0gRldtoCF7ncAI',NULL,NULL),
(1084,'St Mungo’s Wellness Centre','https://static1.squarespace.com/static/5d2e1c7000a7eb000112d289/t/5f511168b060de16bdb9b693/1604314945189/?format=1500w','Life and Soul Counselling is British Association for Counselling and Psychotherapy (BACP) organisation, offering counselling to adults, children and couples.',NULL,NULL,'ChIJxfYDCIHDh0gRoujJkLEcZTM',NULL,NULL),
(1085,'Stills: Centre for Photography','https://ithriveedinburgh.org.uk/wp-content/uploads/2020/10/Stills-Centre-for-Photography.jpg','Stills School is an alternative photography school delivered in two distinct stages, people can develop photography skills at a pace and level that suits everyone.',NULL,NULL,'ChIJnTNt84_Hh0gRgtRPE8FNnFM',NULL,NULL),
(1086,'Street Soccer Scotland','https://www.streetsoccerscotland.org/static/images/logo-white.svg','Daytime football sessions that are open to all abilities and genders',NULL,NULL,'ChIJFXsBJgW4h0gRYcK1DZ7fV5M',NULL,NULL),
(1087,'Streetwork, Simon Community Scotland','https://www.streetwork.org.uk/wp-content/uploads/2019/08/streetwork-banner-2.jpg','The Holyrood Hub offers access to practical amenities (showers, laundry, storage) for people who are sleeping rough as well as a digital zone offering online access.',NULL,NULL,'ChIJiQrfvYXHh0gRoP9bE-tPeMs',NULL,NULL),
(1088,'Support in Mind Scotland','https://ithriveedinburgh.org.uk/wp-content/uploads/2020/10/support-in-mind.jpg','The Stafford Centre aims to help people to manage their mental health, gain greater self-confidence and become more integrated within the community.',NULL,NULL,'ChIJP8sHB43Hh0gRrLVuYVUs1Ec',NULL,NULL),
(1089,'Survivors of Bereavement by Suicide','https://ithriveedinburgh.org.uk/wp-content/uploads/2020/10/SOBS.jpg','A support group for anyone who has lost a person to suicide.',NULL,NULL,'',NULL,NULL),
(1090,'TalkTime Scotland','https://ithriveedinburgh.org.uk/wp-content/uploads/2020/10/TalkTime-Scotland.jpg','TalkTime Scotland offers free professional counselling if disability and/or long-term condition is impacting your life on a day-to-day basis.',NULL,NULL,'ChIJ0x_opN7Hh0gRNYRgS6Fe7o8',NULL,NULL),
(1091,'The Alma Project','https://ithriveedinburgh.org.uk/wp-content/uploads/2020/10/The-Alma-Project.jpg','The Alma Project uses the arts as a therapeutic tool to support people with mental health difficulties.',NULL,NULL,'ChIJJ0sAzkG4h0gRmt-7EAlokoE',NULL,NULL),
(1092,'The Joshua Nolan Foundation','https://ithriveedinburgh.org.uk/wp-content/uploads/2020/10/Joshua-Nolan-foundation.jpg','The Joshua Nolan Foundation’s aim is to reduce the numbers of suicide by helping to fund quality counselling sessions for those who desperately need it, while also improving awareness of the issue across Edinburgh.',NULL,NULL,'',NULL,NULL),
(1093,'The Prince’s Trust','https://www.princes-trust.org.uk/cs/pt/assets/Princes_Trust_Logo_Start_Something2.png','Enterprise programme is designed for people who are newly self-employed or are interested in starting their own business.',NULL,NULL,'',NULL,NULL),
(1094,'The Royal Voluntary Service','https://volunteering.royalvoluntaryservice.org.uk/pics/vol-logo.jpg','The Out and About group provide opportunities for older people to meet each other and go on outings together to local places of interest.',NULL,NULL,'ChIJ5WJ2jQvHh0gR22V5159Kv_I',NULL,NULL),
(1095,'The Sorted Project','https://ithriveedinburgh.org.uk/wp-content/uploads/2020/10/The-Sorted-Project.jpg','The Sorted Project provides access to stable and quality recovery reintegration, motivation and life skills for people who have experienced ill health due to substance use and associated mental health difficulties.',NULL,NULL,'ChIJk6JmAJHHh0gR234BvGRg6cY',NULL,NULL),
(1096,'The Spark Counselling Edinburgh','https://www.thespark.org.uk/wp-content/uploads/2017/05/logo.png','The Spark is a leading provider of marriage counselling, having been established in 1965 as a marriage counselling provider.',NULL,NULL,'ChIJ5WJ2jQvHh0gR22V5159Kv_I',NULL,NULL),
(1097,'The University of Edinburgh','https://www.ed.ac.uk/sites/all/themes/uoe/assets/logo.png','Hope Park Counselling Centre is part of the University of Edinburgh and is a practice and research centre for qualified counsellors and counsellors in training.',NULL,NULL,'ChIJM5vqtIPHh0gRNs5dokw9K4w',NULL,NULL),
(1098,'Thistle Foundation','https://ithriveedinburgh.org.uk/wp-content/uploads/2020/10/Thistle-Logo-Colour-Vibrant-2.jpg','The Thistle Foundation supports people living with long term health conditions or facing challenging life situations to find ways to better manage and live well.',NULL,NULL,'ChIJT0OFgvq4h0gR9SmbZN7fRLo',NULL,NULL),
(1099,'Venture Scotland','https://ithriveedinburgh.org.uk/wp-content/uploads/2020/11/Venture-Scotland.png','Venture Scotland believe that every young adult should have the opportunity to learn how to change so that they lead a happier, healthier, and more fulfilled life.',NULL,NULL,'ChIJfdAiBnO4h0gRGm2chNROJZo',NULL,NULL),
(1100,'Victim Support Scotland','https://ithriveedinburgh.org.uk/wp-content/uploads/2020/10/Victim-Support-Scotland.jpg','People aged 12 years old and over and a victim of crime needing support',NULL,NULL,'ChIJ2QFxN4HHh0gRF8JwuyYUZYA',NULL,NULL),
(1101,'Voices Of Carers Across Lothians','https://www.vocal.org.uk/wp-content/themes/flat-bootstrap-child/images/logo-vocal-white.png','VOCAL runs training and leisure events information and support to carers',NULL,NULL,'ChIJySXDOgm4h0gRk5PYUFhP3x8',NULL,NULL),
(1102,'Voices Of Carers Across Lothians (VOCAL) Edinburgh','https://www.vocal.org.uk/wp-content/themes/flat-bootstrap-child/images/logo-vocal-white.png','This service aims to collect and share the views of carers about mental health services in Edinburgh.',NULL,NULL,'ChIJySXDOgm4h0gRk5PYUFhP3x8',NULL,NULL),
(1103,'Voices Of Carers Across Lothians VOCAL','','VOCAL runs training and leisure events information and support to carers',NULL,NULL,'ChIJB25BufDHh0gR097hj09n5wU',NULL,NULL),
(1104,'Volunteer Edinburgh','https://www.volunteeredinburgh.org.uk/wp-content/themes/volunteeredinburgh/im/logo.svg','The service for job seekers move towards employment.',NULL,NULL,'ChIJt4q_0wu4h0gRpklzSOnYbyY',NULL,NULL),
(1105,'Waverley Care','https://www.waverleycare.org/application/themes/waverley_care/images/waverley-logo.svg','Holistic support for people living with or affected by HIV, hepatitis C or poor sexual health across Edinburgh and the Lothians.',NULL,NULL,'ChIJvyLzbo3Hh0gRNe9xQeeIvAw',NULL,NULL),
(1106,'Wellbeing Scotland','https://ithriveedinburgh.org.uk/wp-content/uploads/2020/10/WS-Logo-RGB-Keyline-COL-60.png','Wellbeing Scotland offers a range of support to people whose adverse life circumstances have had any impact on their wellbeing',NULL,NULL,'ChIJQZ5uhtl9iEgRH1-RXBEELLQ',NULL,NULL),
(1107,'Wheatley Care','','Mental health resource centre that provides a range of meaningful group activities',NULL,NULL,'ChIJgyC4LJ_Hh0gRfqA4L0SxRlU',NULL,NULL),
(1108,'Who Cares? Scotland','https://www.whocaresscotland.org/wp-content/themes/wcs/dist/images/logo.png','A national voluntary organisation, working with care experienced young people and care leavers across Scotland.',NULL,NULL,'ChIJn4xKy51GiEgRzoDTcQsy94k',NULL,NULL),
(1109,'Mind','','We provide advice and support to empower anyone experiencing a mental health problem. We campaign to improve services, raise awareness and promote understanding.',NULL,NULL,'',NULL,NULL),
(1110,'The Mix','https://www.themix.org.uk/wp-content/themes/connected/images/TheMix_logo.png','We’re here to take on the embarrassing problems, weird questions, and please-don’t-make-me-say-it-out-loud thoughts you have. We give you the information and support you need to deal with it all. Because you can. Because you’re awesome.',NULL,NULL,'ChIJ-4Fuha0EdkgR9uf6iqcK5aA',NULL,NULL),
(1111,'YoungMinds','https://youngminds.org.uk/assets/logos/youngminds-logo.svg','We’re the UK’s leading charity fighting for children and young people\'s mental health.',NULL,NULL,'',NULL,NULL),
(1112,'Childline','','A free, private and confidential service where you can talk about anything.',NULL,NULL,'ChIJa5cEULAcdkgRbuM4jkOMfhE',NULL,NULL),
(1113,'Kooth','https://www.kooth.com/tavern-static/logo.kooth.f045b600.svg','Online mental wellbeing community',NULL,NULL,'',NULL,NULL),
(1114,'Anxiety UK','https://www.anxietyuk.org.uk/wp-content/uploads/2020/08/Group-464@2x.png','Anxiety UK offers support, advice and information on a range of anxiety, stress and anxiety-based depression conditions. ',NULL,NULL,'ChIJF2k7PgOue0gRhnZLUEJgDgc',NULL,NULL),
(1115,'Bipolar UK','','Supporting everyone affected by bipolar.',NULL,NULL,'ChIJeQeQxB8FdkgRQK61y5PNGhE',NULL,NULL),
(1116,'Mens Health Forum','','All men and boys - particularly those in the most disadvantaged areas and communities - will have the information, services and treatments they need to live healthier, longer and more fulfilling lives.',NULL,NULL,'ChIJXf_dJaQcdkgRL-doJzv1-fU',NULL,NULL),
(1117,'No Panic','https://nopanic.org.uk/wp-content/uploads/2018/06/No-Panic-Avatar-207x114.png','Helps people who suffer from Panic Attacks, Phobias, Obsessive Compulsive Disorders and other related anxiety disorders including those people who are trying to give up Tranquillizers',NULL,NULL,'ChIJI2rB4qp_cEgRSrj1tag27pY',NULL,NULL),
(1118,'OCD Action','http://www.ocdaction.org.uk/sites/all/themes/ocd/images/logo.png','OCD Action works for a society where OCD is better understood and diagnosed quickly, where appropriate treatment options are open and accessible, where support and information is readily available and where nobody feels ashamed to ask for help.',NULL,NULL,'ChIJJctHGVobdkgREzFJ0C6uDh0',NULL,NULL),
(1119,'OCD UK','https://www.ocduk.org/wp-content/uploads/2020/07/OCDUK-horizontal-1134x768-1.jpg','We provide advice, information, and support services for those affected by OCD, and campaign to end the trivialisation and stigma of OCD.',NULL,NULL,'ChIJlxni_0LzeUgRg6H1JoZK5Qc',NULL,NULL),
(1120,'Papyrus','https://www.papyrus-uk.org/wp-content/uploads/2018/07/logo.png.webp','We exist to reduce the number of young people who take their own lives by shattering the stigma around suicide and equipping young people and their communities with the skills to recognise and respond to suicidal behaviour.',NULL,NULL,'ChIJVXgSFUQCe0gRtYtT3thOB_U',NULL,NULL),
(1121,'Sane','','SANE provides emotional support, guidance and information to anyone affected by mental illness, including families, friends and carers.',NULL,NULL,'ChIJw-vzXXEbdkgR7IEKvS-LwgY',NULL,NULL),
(1122,'NSPCC','','We’ve been looking out for children for over 130 years',NULL,NULL,'ChIJa5cEULAcdkgRbuM4jkOMfhE',NULL,NULL),
(1123,'Refuge','https://www.refuge.org.uk/wp-content/uploads/2015/09/refuge-logo.jpg','We aim to empower women and children to rebuild their lives, free from violence and fear. We provide a range of life-saving and life-changing services, and a voice for the voiceless',NULL,NULL,'ChIJj-mBAUkDdkgRIK7MeEppqyM',NULL,NULL),
(1124,'Al-Anon Family Groups UK & Eire','https://www.al-anonuk.org.uk/workspace/images/logo.svg','Our members provide meetings in all major towns and cities and are committed to being there for you when you need help. ',NULL,NULL,'ChIJK2KdyKUEdkgRVz7cK0Ggwyk',NULL,NULL),
(1125,'Nacoa','https://www.nacoa.org.uk/static/images/logoNacoa.png','Address the needs of children growing up in families where one or both parents suffer from alcoholism or a similar addictive problem. ',NULL,NULL,'',NULL,NULL),
(1126,'NHS','','Drinkline is the national alcohol helpline. If you\'re worried about your own or someone else\'s drinking, you can call this free helpline in complete confidence. ',NULL,NULL,'',NULL,NULL),
(1127,'Smart Recovery','https://smartrecovery.org.uk/wp-content/uploads/2020/10/Smart-Recovery_Horizontal-tagline-1-01.png','Promotes choice in recovery through a national network of mutual-aid meetings and online training programmes with comprehensive teaching materials and manuals.',NULL,NULL,'ChIJoVCg77-xe0gROnK_6REAbJs',NULL,NULL),
(1128,'Cruse Bereavement Care','https://www.cruse.org.uk/sites/all/themes/bootstrap_cruse_www_2018/images/logo/cruse-logo.png','All bereaved people have somewhere to turn when someone dies',NULL,NULL,'ChIJ5fx2UC4MdkgRtV75XIV09G4',NULL,NULL),
(1129,'Rape Crisis','','We exist to improve services and promote the needs and rights of women and girls who have experienced sexual abuse, rape and all forms of sexual violence. We also work towards the elimination of sexual violence and abuse, raising awareness in the wider community and with government.',NULL,NULL,'',NULL,NULL),
(1130,'Victim Support ','','VictimSupport.org is a resource to help victims of abuse, fraud, and other injustices find the support they need to move forward in their lives.',NULL,NULL,'',NULL,NULL),
(1131,'Cocaine Anonymous','https://cocaineanonymous.org.uk/wp-content/uploads/2018/05/Cocaine-Anonymous-Logo-Transparency-3292-1024x1024.png','Cocaine Anonymous is a fellowship of men and women who share their experience, strength and hope with each other so that they may solve their common problem and help others to recover from their addiction. ',NULL,NULL,'',NULL,NULL),
(1132,'Frank','https://www.talktofrank.com/ui/svg/logo-frank--alt.svg','Drug resources',NULL,NULL,'',NULL,NULL),
(1133,'Marijuana Anonymous UK','http://www.marijuana-anonymous.org.uk/images/ma-logo-lores.png','Marijuana Anonymous is a fellowship of men and women who share our experience, strength, and hope with each other that we may solve our common problem and help others to recover from marijuana addiction.',NULL,NULL,'',NULL,NULL),
(1134,'Narcotics Anonymous UK','https://ukna.org/sites/ukna.org/files/logos/UKNA.png','NA is a non-profit fellowship or society of men and women for whom drugs had become a major problem',NULL,NULL,'',NULL,NULL),
(1135,'Gamblers Anonymous','https://www.gamblersanonymous.org.uk/images/logos/web-logo.svg','Gamblers Anonymous is a fellowship of men and women who have joined together to do something about their own gambling problem and to help other compulsive gamblers do the same.',NULL,NULL,'',NULL,NULL),
(1136,'GamAnon UK','http://gamanon.org.uk/wp-content/uploads/2015/04/cropped-Gamanon-logo-225212.png','Gam-Anon is a fellowship of men and  women who are husbands, wives, partners, relatives or close friends of someone with a gambling problem  who also have been affected by this gambling problem.',NULL,NULL,'',NULL,NULL),
(1137,'BeGambleAware','https://www.begambleaware.org/assets/images/logo.png','We provide information to help people make informed decisions about their gambling. We will help you to find out more about gambling and what safer gambling means, to understand and recognise the risks of gambling, and show you where to go for further information, help and support should you need it.',NULL,NULL,'',NULL,NULL),
(1138,'Family Lives','https://app.pelorous.com/public/cms/209/432/2/2/OoGyON_web.png?v=1','Family Lives provides targeted early intervention and crisis support to families who are struggling. The issues we support families with include family breakdown, challenging relationships and behaviour, debt, and emotional and mental wellbeing.',NULL,NULL,'ChIJxQ8tvJg8dkgRDObQI-AvC9U',NULL,NULL),
(1139,'Relate','https://www.relate.org.uk/sites/all/modules/custom/relate_global_regions/img/logo.png','We’re the UK\'s largest provider of relationship support, and last year we helped over two million people of all ages, backgrounds, sexual orientations and gender identities to strengthen their relationships.',NULL,NULL,'ChIJ2ac8xZoOeUgRcUmI_aHbuP4',NULL,NULL),
(1140,'Clic','https://clic-uk.org/wp-content/themes/accent/images/logo.svg','A free online community here to support everyone with their mental health',NULL,NULL,'ChIJnTubpe4EdkgRpg-8HLdcu58',NULL,NULL),
(1141,'Nightline Association','https://www.nightline.ac.uk/wp-content/uploads/2014/08/imaging.jpg','Nightline is a student listening service which is open at night and run by students for students. ',NULL,NULL,'',NULL,NULL),
(1142,'Shout','','If you are feeling anxious, worried, overwhelmed or struggling to cope, here are some resources to help you feel calmer.',NULL,NULL,'',NULL,NULL),
(1143,'BACP','','As the UK\'s leading professional body for the counselling professions, we offer unique and exclusive ways for advertisers to reach over 50,000 counsellors and psychotherapists.',NULL,NULL,'ChIJSyQrABpCd0gRrrw3s22BXz4',NULL,NULL),
(1144,'Pandas','https://pandasfoundation.org.uk/wp-content/uploads/2020/07/PANDAS-Logo.jpg','Support service for families and their networks who may be suffering with perinatal mental illness, including prenatal (antenatal) and postnatal depression.',NULL,NULL,'ChIJcWJRroW6ekgRCJIJZ5EEh_8',NULL,NULL),
(1145,'Citizens Advice','https://www.citizensadvice.org.uk/Static/images/logos/cas-logo_100px.png','Advice and support service',NULL,NULL,'',NULL,NULL),
(1146,'LGBT Switchboard','https://switchboard.lgbt/wp-content/themes/public-theme/img/logo.png','We are a safe space for anyone to discuss anything, including sexuality, gender identity, sexual health and emotional wellbeing.',NULL,NULL,'ChIJo9cSrGcbdkgRXTYYhmODq2s',NULL,NULL),
(1147,'No More Panic','https://www.nomorepanic.co.uk/wp-content/uploads/2014/08/logo-wide.png','This site provides valuable information for sufferers and carers of people with Panic, Anxiety, Phobias and Obsessive Compulsive Disorders (OCD). ',NULL,NULL,'',NULL,NULL),
(1148,'Aberlour Outreach (Dundee) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1149,'Tayside Arrest Referral Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1150,'We Are With You (Fife) ','https://www.wearewithyou.org.uk/static/img/logo/brand-logo-stacked.85d318636c49.svg','Community Based',NULL,NULL,'',NULL,NULL),
(1151,'We Are With You (Islay) ','https://www.wearewithyou.org.uk/static/img/logo/brand-logo-stacked.85d318636c49.svg','Community Based',NULL,NULL,'',NULL,NULL),
(1152,'We Are With You (Argyll & Bute) ','https://www.wearewithyou.org.uk/static/img/logo/brand-logo-stacked.85d318636c49.svg','Community Based',NULL,NULL,'',NULL,NULL),
(1153,'We Are With You (Dumfries) ','https://www.wearewithyou.org.uk/static/img/logo/brand-logo-stacked.85d318636c49.svg','Community Based',NULL,NULL,'',NULL,NULL),
(1154,'We Are With You (Stranraer) ','https://www.wearewithyou.org.uk/static/img/logo/brand-logo-stacked.85d318636c49.svg','Community Based',NULL,NULL,'',NULL,NULL),
(1155,'We Are With You - Dundee Direct Access Service ','https://www.wearewithyou.org.uk/static/img/logo/brand-logo-stacked.85d318636c49.svg','Community Based',NULL,NULL,'',NULL,NULL),
(1156,'We Are With You - East Ayrshire Recovery Service ','https://www.wearewithyou.org.uk/static/img/logo/brand-logo-stacked.85d318636c49.svg','Community Based',NULL,NULL,'',NULL,NULL),
(1157,'We Are With You - Families Plus Service ','https://www.wearewithyou.org.uk/static/img/logo/brand-logo-stacked.85d318636c49.svg','Community Based',NULL,NULL,'',NULL,NULL),
(1158,'We Are With You - North West Recovery Hub (Glasgow) ','https://www.wearewithyou.org.uk/static/img/logo/brand-logo-stacked.85d318636c49.svg','Community Based',NULL,NULL,'',NULL,NULL),
(1159,'We Are With You - South Ayrshire Recovery Service ','https://www.wearewithyou.org.uk/static/img/logo/brand-logo-stacked.85d318636c49.svg','Community Based',NULL,NULL,'',NULL,NULL),
(1160,'Addiction Recovery Centre (Kirkintilloch) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1161,'Addiction Services (NHS Borders) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1162,'Addiction Services (NHS Fife) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1163,'Addictions Support and Counselling (ASC) Forth Valley (Falkirk) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1164,'Adolescent Substance Use Service (ASUS) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1165,'Adolescent Substance Use Service (ASUS) (East Lothian) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1166,'Angus Integrated Drug & Alcohol Recovery Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1167,'Alcohol & Drugs Action ','','Community Based',NULL,NULL,'',NULL,NULL),
(1168,'Alcohol Drugs Support South West Scotland (Castle Douglas) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1169,'Alcohol Drugs Support South West Scotland (Dumfries) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1170,'Alcohol Drugs Support South West Scotland (Stranraer) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1171,'Youth Action Team (Inverness) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1172,'Drug Treatment & Testing Order (Dundee) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1173,' Drug Treatment & Testing Order (Edinburgh,East and Midlothian) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1174,'West Lothian NHS Addiction Service ','','Community Based,Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1175,'Drug Treatment & Testing Order (Fife) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1176,'West Lothian Drug and Alcohol Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1177,'Drug Treatment & Testing Order (Glasgow) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1178,'Alternatives (Clydebank) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1179,'Drug Treatment & Testing Order (Highland) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1180,'Alcohol and Drug Recovery Service (Glasgow West) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1181,'Drug Treatment & Testing Order (Inverclyde) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1182,'Alternatives (Dumbarton) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1183,'Drug Treatment & Testing Order (Lanarkshire) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1184,'Web Project (Angus) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1185,'Apex Scotland Services (Stranraer) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1186,'Drug Treatment & Testing Order (Renfrewshire) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1187,'Web Project / Streets Ahead ','','Community Based',NULL,NULL,'',NULL,NULL),
(1188,'Drug Treatment & Testing Order (West Lothian) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1189,'Alcohol and Drug Recovery Service (Glasgow East) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1190,'East Dunbartonshire Alcohol and Drugs Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1191,'Apex Scotland Services (Dumfries) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1192,'Veterans Substance Misuse Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1193,'East Lothian Substance Misuse Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1194,'East Renfrewshire Community Addiction Team ','','Community Based',NULL,NULL,'',NULL,NULL),
(1195,'East Renfrewshire Community Recovery Team ','','Community Based',NULL,NULL,'',NULL,NULL),
(1196,'Edinburgh Access Practice ','','Community Based',NULL,NULL,'',NULL,NULL),
(1197,'Eriskay House ','','Community Based',NULL,NULL,'',NULL,NULL),
(1198,'FASS Community Drug Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1199,'Fife Intensive Rehabilitation Substance Misuse Team (FIRST) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1200,'Argyll & Bute Addiction Service (Oban) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1201,'First Base Agency ','','Community Based',NULL,NULL,'',NULL,NULL),
(1202,'Forth Valley Substance Misuse Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1203,'Glasgow Drug Crisis Centre (Turning Point Scotland) ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1204,'Argyll & Bute Addiction Team (Bute) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1205,'Turning Point Scotland - Edinburgh Substance Misuse Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1206,'North Aberdeenshire Recovery Service (Banff) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1207,'North Aberdeenshire Recovery Service (Peterhead) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1208,'Turning Point Scotland (218 Service) ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1209,'Turnaround Residential Unit (Paisley) ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1210,'Teen Challenge UK ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1211,'Integrated Substance Misuse Team (Dundee) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1212,'Tayside Council on Alcohol - Adult Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1213,'Argyll & Bute Addiction Team (Cowal) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1214,'Argyll & Bute Addiction Team (Kintyre) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1215,'Argyll & Bute Addiction Team (Mid Argyll) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1216,'Crossreach Tayside Support Services ','','Community Based',NULL,NULL,'',NULL,NULL),
(1217,'Barnardo\'s Axis Service (Falkirk) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1218,'Barnardo\'s Connect (Aberdeen) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1219,'Barnardo\'s Freagarrach Project (Stirling) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1220,'Barnardo\'s Threads (Paisley) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1221,'Community Mental Health Team (Orkney) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1222,'Community Addiction Recovery Service (CAReS) ','','Community Based-1',NULL,NULL,'',NULL,NULL),
(1223,'Substance Misuse Service - South West Recovery Hub ','','Community Based',NULL,NULL,'',NULL,NULL),
(1224,'Substance Misuse Service (Grampian) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1225,'Substance Misuse Service - South East Recovery Hub ','','Community Based',NULL,NULL,'',NULL,NULL),
(1226,'Substance Misuse Service - North West Recovery Hub ','','Community Based',NULL,NULL,'',NULL,NULL),
(1227,'Bethany Christian Centre ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1228,'Black & Minority Ethnic Drug & Alcohol Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1229,'Cairn Centre Harm Reduction Service (Dundee) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1230,'Caithness Alcohol and Drug Service (Thurso) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1231,'Substance Misuse Service - North East Recovery Hub ','','Community Based',NULL,NULL,'',NULL,NULL),
(1232,'Caithness Alcohol and Drug Service (Wick) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1233,'Substance Misuse In-patient Service (Inverness) ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1234,'Castle Craig Hospital ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1235,'Substance Misuse Co-ordinator (Western Isles)  ','','Community Based',NULL,NULL,'',NULL,NULL),
(1236,'Circle (Harbour Project) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1237,'Circle (West Lothian) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1238,'NHS Specialist Drug and Alcohol Service (Dumfries & Galloway) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1239,'Clued Up Project ','','Community Based',NULL,NULL,'',NULL,NULL),
(1240,'Special Needs in Pregnancy Services (Renfrewshire) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1241,'West Dunbartonshire Addiction Services (Clydebank) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1242,'Community Alcohol & Drug Service (Forth Valley) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1243,'Special Needs in Pregnancy Services (Inverclyde) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1244,'Special Needs in Pregnancy Services (Glasgow) ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1245,'Special Needs in Pregnancy Services (Dunbartonshire) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1246,'Harm Reduction Team NHS Lothian ','','Community Based',NULL,NULL,'',NULL,NULL),
(1247,'Community Substance Misuse Service (Aberdeenshire) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1248,'Connecting Carers ','','Community Based',NULL,NULL,'',NULL,NULL),
(1249,'Cothrom Eile ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1250,'CPN Team (Lewis & Harris) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1251,'CPN Team (Uists & Barra) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1252,'CREW ','','Community Based',NULL,NULL,'',NULL,NULL),
(1253,'Drugs Alcohol & Psychotherapies Limited (DAPL) services for young people ','','Community Based',NULL,NULL,'',NULL,NULL),
(1254,'Drugs Alcohol & Psychotherapies Limited (DAPL) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1255,'Perth & Kinross Drug and Alcohol Team ','','Community Based',NULL,NULL,'',NULL,NULL),
(1256,'Drug Court Supervision & Treatment Team (Glasgow) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1257,'Drug Liaison Midwife ','','Community Based',NULL,NULL,'',NULL,NULL),
(1258,'Drug Treatment & Testing Order (Aberdeen City) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1259,' Drug Treatment & Testing Order (Argyll,Bute and Dunbartonshire) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1260,'Drug Treatment & Testing Order (Ayrshire Criminal Justice Partnership) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1261,'Drug Treatment & Testing Order (Borders) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1262,'Drug Treatment & Testing Order (Dumfries & Galloway) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1263,'Substance Misuse Recovery Service (Shetland) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1264,'Alcohol and Drug Recovery Service (Glasgow South West) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1265,'Alcohol and Drug Recovery Service (Glasgow South East) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1266,'Alcohol and Drug Recovery Service (Glasgow Greater Pollok) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1267,'Highland Alcohol and Drug Advice & Support Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1268,'Harm Reduction Service (Lanarkshire) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1269,'Alcohol and Drug Recovery Service (Glasgow South) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1270,'South Ayrshire Health & Social Care Partnership Community NHS Addiction Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1271,'Social Work Department (Renfrew Area Office) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1272,'Social Work Addictions Team (West Lothian) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1273,'Simpson House Counselling and Recovery Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1274,'Second Chance Project ','','Community Based',NULL,NULL,'',NULL,NULL),
(1275,'Scottish Borders CHIMES Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1276,'Salvation Army (Falkirk) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1277,'Routes Out ','','Community Based',NULL,NULL,'',NULL,NULL),
(1278,'Ritson Clinic ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1279,'Re-Solv (Scotland) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1280,'Renfrewshire Drug Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1281,'Helensburgh and Lomond Addiction Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1282,'Drug & Alcohol Intervention Team ','','Community Based',NULL,NULL,'',NULL,NULL),
(1283,'Homeless Addiction Team (Glasgow) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1284,'Homeless Outreach Project ','','Community Based',NULL,NULL,'',NULL,NULL),
(1285,'Integrated Drug Service (Aberdeen) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1286,'Alcohol and Drug Recovery Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1287,'Rankeillor Initiative ','','Community Based',NULL,NULL,'',NULL,NULL),
(1288,'Rainbow House ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1289,'Priory Addiction Treatment Programme ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1290,'ISSU 18 (Young People\'s Substance Use) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1291,'Pre Birth Team (New Expectations) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1292,'Addiction Recovery Team (Airdrie) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1293,'Addiction Recovery Team (Bellshill) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1294,'Jericho House (Men Only) ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1295,'Addiction Recovery Team (Coatbridge) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1296,'Phoenix Futures ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1297,'Addiction Recovery Team (Cumbernauld) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1298,'Addiction Recovery Team (Motherwell) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1299,'Addiction Recovery Team (Wishaw) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1300,'Glasgow Image and Performance Enhancing Drugs Clinic (IPEDS) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1301,'LEAP (Lothian & Edinburgh Abstinence Programme) ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1302,'Web Project Key to Change ','','Community Based',NULL,NULL,'',NULL,NULL),
(1303,'Kintyre Alcohol and Drugs Advisory Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1304,'West Dunbartonshire Addiction Services (Dumbarton) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1305,'Ward 5 Inpatient Addiction Services ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1306,'Liber8 (Lanarkshire) Ltd ','','Community Based',NULL,NULL,'',NULL,NULL),
(1307,'Over-Count Drugs Information Agency ','','Community Based',NULL,NULL,'',NULL,NULL),
(1308,'Change Grow Live North West ','','Community Based',NULL,NULL,'',NULL,NULL),
(1309,'Change Grow Live South East ','','Community Based',NULL,NULL,'',NULL,NULL),
(1310,'Osprey House ','','Community Based',NULL,NULL,'',NULL,NULL),
(1311,'Change Grow Live South West ','','Community Based',NULL,NULL,'',NULL,NULL),
(1312,'Mid and East Lothian Drugs (MELD) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1313,'Moving On (Inverclyde) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1314,'Orkney Alcohol Counselling & Advisory Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1315,'Midpark Hospital ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1316,'North Ayrshire Drug & Alcohol Recovery Service (NADARS) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1317,'Oban Addiction Support and Information Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1318,'North Edinburgh Drug & Alcohol Centre/Complex & Multiple Needs Team ','','Community Based',NULL,NULL,'',NULL,NULL),
(1319,'Alcohol and Drug Recovery Service (Glasgow North East) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1320,'Midlothian Young People\'s Advice Service (MYPAS) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1321,'Addiction Services NHS (East Ayrshire) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1322,' Alcohol,Drugs BBV Social Work Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1323,'Substance Misuse Service (Midlothian) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1324,'Health Opportunities Team (HOT) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1325,'Jericho House (Women Only) ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1326,' The Junction,Young People,Health & Wellbeing ','','Community Based',NULL,NULL,'',NULL,NULL),
(1327,'We Are With You - Borders ','','Community Based',NULL,NULL,'',NULL,NULL),
(1328,'Abbeycare Scotland ','','Residential/In-Patient',NULL,NULL,'',NULL,NULL),
(1329,'North Aberdeenshire Drug & Alcohol Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1330,'Survivor Trauma Abuse and Addictions Recovery Service ','','Community Based',NULL,NULL,'',NULL,NULL),
(1331,'Argyll & Bute Addiction Team (Islay) ','','Community Based',NULL,NULL,'',NULL,NULL),
(1332,'Hillcrest Futures ','','Community Based',NULL,NULL,'',NULL,NULL),
(1333,'Relationships Scotland Orkney ','','Community Based',NULL,NULL,'',NULL,NULL),
(1334,'Tayside Council on Alcohol - Young Person Service ','','Community Based',NULL,NULL,'',NULL,NULL);
