Insert into Miricyl.Country values(101,'Scotland');
Insert into Miricyl.Country values(102,'England');
Insert into Miricyl.Country values(103,'Wales');
Insert into Miricyl.Country values(104,"Northen Ireland");
Insert into Miricyl.Country values(105,"United Kingdom");
Insert into Miricyl.Gender values(101,'Female');
Insert into Miricyl.Gender values(102,'Male');
Insert into Miricyl.Gender values(103,'Both');

Insert into Miricyl.Needs Values(101,'Abuse','Abuse or bullying');
Insert into Miricyl.Needs Values(102,'Addiction','Addiction');
Insert into Miricyl.Needs Values(103,'Alcohol','Addiction');
Insert into Miricyl.Needs Values(104,'Anger','Anxiety, anger or stress');
Insert into Miricyl.Needs Values(105,'Anxiety','Anxiety, anger or stress');
Insert into Miricyl.Needs Values(106,'Bereavement','');
Insert into Miricyl.Needs Values(107,'Body image','Body image or eating disorders');
Insert into Miricyl.Needs Values(108,'Bullying','Abuse or bullying');
Insert into Miricyl.Needs Values(109,'Care','');
Insert into Miricyl.Needs Values(110,'Debt','Debt or unemployment');
Insert into Miricyl.Needs Values(111,'Depression','Feeling low or depressed');
Insert into Miricyl.Needs Values(112,'Discrimination','');
Insert into Miricyl.Needs Values(113,'Domestic Abuse','Domestic Abuse');
Insert into Miricyl.Needs Values(114,'Drugs','Addiction');
Insert into Miricyl.Needs Values(115,'Eating disorders','Body image or eating disorders');
Insert into Miricyl.Needs Values(116,'Feeling low','Feeling low or depressed');
Insert into Miricyl.Needs Values(117,'Gender identity','LGBTQ+ or gender identity');
Insert into Miricyl.Needs Values(118,'General Mental Health','');
Insert into Miricyl.Needs Values(119,'Into work /unemployment','Debt or unemployment');
Insert into Miricyl.Needs Values(120,'Involved in crime','Crime');
Insert into Miricyl.Needs Values(121,'LGBTQ+','LGBTQ+ or gender identity');
Insert into Miricyl.Needs Values(122,'Loneliness','');
Insert into Miricyl.Needs Values(123,'Money','Debt or unemployment');
Insert into Miricyl.Needs Values(124,'New parent','Pregnancy and Parenting');
Insert into Miricyl.Needs Values(125,'Panic Attacks','Anxiety, anger or stress');
Insert into Miricyl.Needs Values(126,'Parenting','Pregnancy and Parenting');
Insert into Miricyl.Needs Values(127,'Pregnant','Pregnancy and Parenting');
Insert into Miricyl.Needs Values(128,'Ralationship issue','');
Insert into Miricyl.Needs Values(129,'Self harm','Suicide or Self-harm');
Insert into Miricyl.Needs Values(130,'Sleep','Sleeping problems');
Insert into Miricyl.Needs Values(131,'Stress','Anxiety, anger or stress');
Insert into Miricyl.Needs Values(132,'Suicide','Suicide or Self-harm');
Insert into Miricyl.Needs Values(133,'Victim of crime','Crime');

Insert into Miricyl.Type Values(101,'Information');
Insert into Miricyl.Type Values(102,'Helpline');
Insert into Miricyl.Type Values(103,'Face to Face Counselling');
Insert into Miricyl.Type Values(104,'Free services');
Insert into Miricyl.Type Values(105,'Financial help');
Insert into Miricyl.Type Values(106,'Support groups');
Insert into Miricyl.Type Values(107,'Self Help');
Insert into Miricyl.Type Values(108,'Community care');
Insert into Miricyl.Type Values(109,'Online support - Message Boards');
Insert into Miricyl.Type Values(110,'Online support - Video Support Group');
Insert into Miricyl.Type Values(111,'Online support - Chat');
Insert into Miricyl.Type Values(112,'Online support - Text Counselling');
Insert into Miricyl.Type Values(113,'Online support - E-Counselling');
Insert into Miricyl.Type Values(114,'Online support - Video Counselling');

Insert into Miricyl.Personalisation Values(101,'Under 16','Under 18');
Insert into Miricyl.Personalisation Values(102,'16+','');
Insert into Miricyl.Personalisation Values(103,'18+','');
Insert into Miricyl.Personalisation Values(104,'A student','A student');
Insert into Miricyl.Personalisation Values(105,'A parent','A parent');
Insert into Miricyl.Personalisation Values(106,'LGBTQ+','LGBTQ+');
Insert into Miricyl.Personalisation Values(107,'Unemployed','Unemployed');
Insert into Miricyl.Personalisation Values(108,'A carer','A carer');
Insert into Miricyl.Personalisation Values(109,'BAME','BAME');


